name: dev and testing

on:
  push:
    branches:
      - 'dev'

jobs:
  tartis_channel_bot:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, 'wip')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jon4hz/tartis_channel_bot:latest
          context: .
          file: ./channel_bot.Dockerfile
          cache-from: type=registry,ref=jon4hz/tartis_channel_bot:cache
          cache-to: type=registry,ref=jon4hz/tartis_channel_bot:cache

      - 
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      
      - 
        name: Trigger Webhook
        uses: distributhor/workflow-webhook@v1.0.5
        env:
          webhook_url: ${{ secrets.WEBHOOK_DEV_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_DEV_SECRET }}